### ISSUE TITLE
Should this work with Ruby 2.x? Its not for me

### ISSUE THREAD

**Issue by rberger** [postageapp/openssl_pkcs8#2]
I'm running on Max OS X 10.9.3 and rvm. 

I have a simple test script:

```
#!/usr/bin/env ruby
require 'openssl_pkcs8'

key = OpenSSL::PKey::RSA.new(1024)

result = key.to_pem_pkcs8

puts result
```

If I use `ruby-1.9.3-p484` the test script works fine.

If I use rvm to switch to any of the following

```
ruby-2.0.0-p247 [ x86_64 ]
ruby-2.1.0 [ x86_64 ]
ruby-2.1.2 [ x86_64 ]
```

it doesn't work and I get something like:

```
./tst_pkim.rb:6: [BUG] Segmentation fault at 0x00000000000000

...

-- Control frame information -----------------------------------------------
c:0003 p:---- s:0009 e:000008 CFUNC  :to_pem_pkcs8
c:0002 p:0033 s:0006 E:001478 EVAL   ./tst_pkim.rb:6 [FINISH]
c:0001 p:0000 s:0002 E:000438 TOP    [FINISH]

./tst_pkim.rb:6:in `<main>'
./tst_pkim.rb:6:in `to_pem_pkcs8'

-- C level backtrace information -------------------------------------------
0   ruby                                0x00000001002851a6 rb_vm_bugreport + 134
1   ruby                                0x000000010013bc53 report_bug + 307
2   ruby                                0x000000010013bb14 rb_bug + 180
3   ruby                                0x0000000100208599 sigsegv + 153
4   libsystem_platform.dylib            0x00007fff8f4a65aa _sigtramp + 26
5   libcrypto.0.9.8.dylib               0x00007fff8ecba5b5 BN_num_bits + 21
6   ???                                 0x00000000ffffffff 0x0 + 4294967295
```

Is it something in my environment? Or something else?

**Comment by cielavenir** [comment]
Well, perhaps you can use https://github.com/cielavenir/openssl_pkcs8_pure, which also has DSA/EC and jruby support (only RSA though)
